Created README file
vikkushnir/Book-store pull request #15
Opened 2024-05-29 08:19 UTC by vikkushnir

2024-05-30 09:22 UTC, yevheniisynytsia requested changes

2024-05-30 09:22 UTC, yevheniisynytsia commented on README.md
> +[Here]() is a short video presentation of application.
as I understand it is expected to be empty for now?

2024-05-30 09:22 UTC, yevheniisynytsia commented on README.md
> +___
I would also like to see a part about challenges that you've faced during development and how you overcame those. Also you may add some possible improvements part

2024-05-30 09:22 UTC, yevheniisynytsia commented on .env.sample
> +SECRET_KEY=<jwt-secret-string>
let's also include a "real" env file with some mock data so that it is easily created. 
You can use you env file but with removed password

2024-06-10 08:35 UTC, karma-o approved these changes
Looks very cool, love the effort on all that!

2024-06-10 08:40 UTC, karma-o commented
forgot to mention, would also be nice to have a simple user and admin credentials to provide the visitor of your project an opportunity to test all endpoints, including admin-only

2024-06-27 10:09 UTC, merged