Added User model, DTOs, repository, service, and AuthController
vikkushnir/Book-store pull request #7
Opened 2024-05-07 13:20 UTC by vikkushnir

Added User model, DTOs, repository, service, and AuthController. Updated swagger

2024-05-08 13:45 UTC, andrii-hoienko requested changes
Nice, left some questions and comments

2024-05-08 13:45 UTC, andrii-hoienko commented on src/main/java/online/book/store/validation/FieldMatch.java
> +    String second();
This fields are not used why do you need them?

2024-05-08 13:45 UTC, andrii-hoienko commented on src/main/java/online/book/store/validation/FieldMatchValidator.java
> +    }
I believe this annotation should work with 2 any fields

2024-05-09 07:59 UTC, karma-o approved these changes
GJ!

2024-05-09 07:59 UTC, karma-o commented on src/main/java/online/book/store/validation/FieldMatchValidator.java
> +        }
```suggestion
        return Objects.equals(fieldValue, fieldMathcValue);
```

2024-05-09 07:59 UTC, karma-o commented on src/main/java/online/book/store/dto/request/user/UserRegistrationRequestDto.java
> +    private String lastName;
I do not think we need a custom message, default ones are usually fine, and we do not need to complex things

2024-05-09 09:30 UTC, merged