Implemented JWT token
vikkushnir/Book-store pull request #9
Opened 2024-05-13 14:15 UTC by vikkushnir

2024-05-14 12:31 UTC, d1sam requested changes
Good job, but there are some minor changes, that should be done according my comments.

2024-05-14 12:31 UTC, d1sam commented on src/main/java/online/book/store/service/user/UserAuthenticationServiceImpl.java
> +        return new UserLoginResponseDto(token);
let's better create `AuthenticationService` with the method `authenticate`

2024-05-14 12:31 UTC, d1sam commented on src/main/resources/application.properties
> +jwt.secret=helloMatesHereIsSecretMessageAbracadabra
let's provide these values from env properties

2024-05-14 12:31 UTC, d1sam commented on src/main/java/online/book/store/service/user/UserAuthenticationService.java
> +    UserLoginResponseDto authenticate(UserLoginRequestDto requestDto);
according to SRP and IS principles of SOLID you should create separate interface for authentication purposes.

2024-05-14 12:31 UTC, d1sam commented on src/main/java/online/book/store/dto/request/user/UserLoginRequestDto.java
> +        @Size(min = 8)
what about max param?

2024-05-14 12:31 UTC, d1sam commented on src/main/java/online/book/store/dto/request/user/UserLoginRequestDto.java
> +        String email,
what about the size?

2024-05-15 10:33 UTC, vovasalyha approved these changes

2024-05-15 10:39 UTC, merged